version: '3.8'

services:
  edge-converter:
    build: .
    volumes:
      - ./config:/app/config
      - ./credentials:/app/credentials
      - ./checkpoint:/app/checkpoint
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=Asia/Kuala_Lumpur
    restart: always
